### ISSUE TITLE
README should document what specific version of Unity to use

### ISSUE THREAD

**Issue by ehgoodenough** [computc/Broken-Fates#2]
### Summary ###

I get a bunch of errors when I try to open this project in Unity 2017.2. For your collaborators, you should document that you are using Unity 2017.3 Free Edition (or whatever specifically you are using)

**Comment by Jragoon** [comment]
Thanks for catching this- I had made my last two commits with 2017.2, then realized the original submit is 2017.3. Added a notice to the README.
